Fix remove_field to use field object instead of string
- schema_editor.remove_field() expects field object, not string
- Use User._meta.get_field('username') to get field instance
- Fix AttributeError: 'str' object has no attribute 'many_to_many'